import 'dart:convert';

/// A single HTTP cookie used for Facebook session export.
class FacebookCookie {
  const FacebookCookie({
    required this.name,
    required this.value,
    required this.domain,
    this.path = '/',
    this.expiresEpoch = 0,
    this.isSecure = true,
    this.isHttpOnly = false,
  });

  final String name;
  final String value;
  final String domain;
  final String path;
  final int expiresEpoch;
  final bool isSecure;
  final bool isHttpOnly;

  Map<String, Object?> toJson() => {
        'name': name,
        'value': value,
        'domain': domain,
        'path': path,
        'expiresEpoch': expiresEpoch,
        'isSecure': isSecure,
        'isHttpOnly': isHttpOnly,
      };

  factory FacebookCookie.fromJson(Map<String, Object?> json) {
    return FacebookCookie(
      name: json['name']?.toString() ?? '',
      value: json['value']?.toString() ?? '',
      domain: json['domain']?.toString() ?? '.facebook.com',
      path: json['path']?.toString() ?? '/',
      expiresEpoch: _asInt(json['expiresEpoch']),
      isSecure: json['isSecure'] == true,
      isHttpOnly: json['isHttpOnly'] == true,
    );
  }

  static int _asInt(Object? value) {
    if (value is int) return value;
    return int.tryParse(value?.toString() ?? '') ?? 0;
  }
}

/// Builds a Cookie request header from stored cookies.
String facebookCookieHeader(Iterable<FacebookCookie> cookies) {
  final parts = <String>[];
  for (final cookie in cookies) {
    if (cookie.name.isEmpty) continue;
    parts.add('${cookie.name}=${cookie.value}');
  }
  return parts.join('; ');
}

/// True when the cookie set looks like a logged-in Facebook session.
bool facebookSessionLooksLoggedIn(Iterable<FacebookCookie> cookies) {
  final names = {for (final c in cookies) c.name};
  return names.contains('c_user') && names.contains('xs');
}

/// Netscape HTTP Cookie File content for yt-dlp `--cookies`.
String netscapeCookieFileContents(Iterable<FacebookCookie> cookies) {
  final buffer = StringBuffer()
    ..writeln('# Netscape HTTP Cookie File')
    ..writeln('# This file was generated by Geonode Download Manager.')
    ..writeln('# https://curl.se/docs/http-cookies.html')
    ..writeln();

  for (final cookie in cookies) {
    if (cookie.name.isEmpty) continue;
    var domain = cookie.domain.trim();
    if (domain.isEmpty) domain = '.facebook.com';
    final includeSubdomains =
        domain.startsWith('.') ? 'TRUE' : 'FALSE';
    if (!domain.startsWith('.') &&
        (domain == 'facebook.com' ||
            domain.endsWith('.facebook.com') ||
            domain == 'fb.com' ||
            domain.endsWith('.fb.com'))) {
      domain = '.$domain';
    }
    final path = cookie.path.isEmpty ? '/' : cookie.path;
    final secure = cookie.isSecure ? 'TRUE' : 'FALSE';
    final expires = cookie.expiresEpoch > 0 ? cookie.expiresEpoch : 0;
    buffer.writeln(
      '$domain\t$includeSubdomains\t$path\t$secure\t$expires\t'
      '${cookie.name}\t${cookie.value}',
    );
  }
  return buffer.toString();
}

List<FacebookCookie> decodeFacebookCookiesJson(String raw) {
  if (raw.trim().isEmpty) return const [];
  final decoded = jsonDecode(raw);
  if (decoded is! List) return const [];
  return decoded
      .whereType<Map>()
      .map((item) => FacebookCookie.fromJson(item.cast<String, Object?>()))
      .where((c) => c.name.isNotEmpty)
      .toList();
}

String encodeFacebookCookiesJson(Iterable<FacebookCookie> cookies) {
  return jsonEncode([for (final c in cookies) c.toJson()]);
}
